export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_COMPANY_PROFILE = 'GET_COMPANY_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_COMPANY_PROFILES = 'GET_COMPANY_PROFILES';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const COMPANY_ACCOUNT_DELETED = 'COMPANY_ACCOUNT_DELETED';
export const CLEAR_COMPANY_PROFILE = 'CLEAR_COMPANY_PROFILE';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const COMPANY_PROFILE_ERROR = 'COMPANY_PROFILE_ERROR';
export const GET_PROFILE_AND_SCORE = 'GET_PROFILE_AND_SCORE';
export const GET_SCORE = 'GET_SCORE';

export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const SEARCH_POST = 'SEARCH_POST';
export const POST_ERROR = 'POST_ERROR';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';


export const SEARCH_QA = 'SEARCH_QA';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTION = 'GET_QUESTION';
export const QUESTION_ERROR = 'QUESTIONS_ERROR';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const ADD_QUESTION = 'ADD_QUESTION';

export const GET_EVENTS = 'GET_EVENTS';
export const EVENT_ERROR = 'EVENT_ERROR';
export const UPDATE_ATTENDANCY = 'UPDATE_ATTENDANCY';
export const GET_EVENT = 'GET_EVENT';

export const ADVERTISE_JOB = 'ADVERTISE_JOB';
export const GET_ADS = 'GET_ADS';
export const JOB_ERROR = 'JOB_ERROR';
export const DELETE_JOB = 'DELETE_JOB';
export const GET_APPLICANTS = 'GET_APPLICANTS';

export const RECOMMENDATION_ERROR = 'RECOMMENDATION_ERROR';
export const GET_RECOMMENDED_JOBS = 'GET_RECOMMENDED_JOBS';

export const ATTEND_JOB_ERROR = 'ATTEND_JOB_ERROR';
export const APPLY_JOB = 'APPLY_JOB';
export const DECLINE_JOB = 'DECLINE_JOB';
export const DECLINE_JOB_ERROR = 'DECLINE-JOB_ERROR';
export const GET_JOB = 'GET_JOB';
